# Generated by Django 5.2.7 on 2025-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='No title', max_length=200),
        ),
    ]
